#!/bin/bash
set -xeuo pipefail

#
# Installs packages and AUR manager.
#

pacman --noconfirm -Syu

pacman -S --needed --noconfirm - < "$BASE_DIR/conf.d/packages"
if [[ "$DESKTOP" == true ]]; then
    pacman -Rns --noconfirm vim # vim and gvim are in conflict...
    pacman -S --needed --noconfirm - < "$BASE_DIR/conf.d/packages-desktop"
fi
