#!/bin/bash
set -xeuo pipefail

#
# Configures pacman.
#

mkdir -p /etc/pacman.d/hooks

cat > /etc/pacman.d/hooks/paccache-upgrade.hook <<EOF
[Trigger]
Operation = Upgrade
Type = Package
Target = *

[Action]
Description = Cleaning pacman cache...
When = PostTransaction
Exec = /usr/bin/paccache -rk2
EOF

cat > /etc/pacman.d/hooks/paccache-remove.hook <<EOF
[Trigger]
Operation = Remove
Type = Package
Target = *

[Action]
Description = Cleaning pacman cache...
When = PostTransaction
Exec = /usr/bin/paccache -ruk0
EOF

cat >> /etc/pacman.conf <<EOF
[multilib]
Include = /etc/pacman.d/mirrorlist
EOF

sed -i 's/#Color/Color/g' /etc/pacman.conf 