#!/bin/bash
set -xeuo pipefail

#
# X11 related configuration.
#

if [[ "$DESKTOP" == false ]]; then
    exit 0
fi

# German Keyboard Layout and no Capslock!
cat > /etc/X11/xorg.conf.d/00-keyboard.conf <<EOF
Section "InputClass"
	Identifier "system-keyboard"
	MatchIsKeyboard "yes"
	Option "XkbLayout" "de"
	Option "XkbOptions" "caps:none"
EndSection
EOF

# Configure lightdm.
cat > /etc/lightdm/lightdm-gtk-greeter.conf <<EOF
[greeter]
background=/usr/share/wallpaper.jpg
theme-name=Adapta
icon-theme-name=Papirus-Adapta
font-name=Roboto 11
EOF

# Configure openbox.
cat > /etc/xdg/openbox/autostart <<EOF
hash xfce4-panel && xfce4-panel &
hash lxqt-notificationd && lxqt-notificationd &
hash feh && feh --bg-fill /usr/share/wallpaper.jpg &
hash numlockx && numlockx &
hash urxvtd && urxvtd &
hash redshift && redshift &
EOF