#!/bin/bash

# Whether or not to run rankmirrors before installation.
RANKMIRRORS=false

# If false, dont install X11 stuff.
DESKTOP=true

# Whether or not to encrypt the `DEVICE`
ENCRYPT=true
CRYPT_VOLUME_NAME="cryptroot"

# Partitions
DEVICE="/dev/nvme0n1"
BOOT_PARTITION="${DEVICE}p1"
HOME_PARTITION="${DEVICE}p2"

# User & Home
HOSTNAME="saso.matejina.arch"
USERNAME="saso"
USERHOME="/home/$USERNAME"

# Passwords
SECRETS_PW=""
DMCRYPT_PW=""
ROOT_PW=""
USER_PW=""
